export const portfolioData = [
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/premier-page.webp',
		title: 'Landing page',
		subtitle: 'PREMIER',
		work: 'Верстка',
		tech: 'HTML + CSS',
		func: 'Слайдер, модальное окно',
		link: 'https://h0lloway.github.io/premier-page/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/lofty.webp',
		title: 'Landing page',
		subtitle: 'Test page',
		work: 'Верстка',
		tech: 'HTML + CSS',
		func: 'Слайдер на маленьком разрешении',
		link: 'https://h0lloway.github.io/lofty-test/',
	},
	{
		type: 'email',
		display: 'none',
		img: 'files/img/portfolio/premier-mail.webp',
		title: 'HTML письмо',
		subtitle: 'PREMIER',
		work: 'Верстка',
		tech: 'Адаптивно',
		func: 'email-рассылка',
		link: 'https://h0lloway.github.io/premier-email/',
	},
	{
		type: 'email',
		display: 'none',
		img: 'files/img/portfolio/mailfit.webp',
		title: 'HTML письмо',
		subtitle: 'Spim.ru',
		work: 'Верстка',
		tech: 'Адаптивно',
		func: 'email-рассылка',
		link: 'https://h0lloway.github.io/mailfit-email/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/enver_studio.webp',
		title: 'Landing page',
		subtitle: '',
		work: 'Верстка',
		tech: 'HTML + CSS',
		func: 'Слайдер',
		link: 'https://h0lloway.github.io/enver_studio/',
	},
	{
		type: 'vue',
		display: 'none',
		img: 'files/img/portfolio/form-vue2.png',
		title: 'Vue приложение',
		subtitle: '',
		work: 'Приложение',
		tech: 'Vue + Vite',
		func: 'переключение опросника в форме',
		link: 'https://form-dubrovin.netlify.app/',
	},
	{
		type: 'vue',
		display: 'none',
		img: 'files/img/portfolio/portfolio1.png',
		title: 'Vue приложение',
		subtitle: 'Портфолио',
		work: 'Приложение',
		tech: 'Vue + Vite',
		func: 'toggle меню на маленьком разрешении',
		link: 'https://dubrovin-portfolio.netlify.app/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/SDP.webp',
		title: 'Сайт магазина мебели',
		subtitle: 'SitDownPls',
		work: 'Верстка',
		tech: 'HTML + CSS(flex + grid)',
		func: 'Слайдер, табы, модальные окна, селекты',
		link: 'https://h0lloway.github.io/SitDownPls__makdu/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/blanchard.webp',
		title: 'Страница галереи',
		subtitle: 'Blanchard - галерея',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex)',
		func: 'Слайдер, табы, модальные окна, аккордион',
		link: 'https://h0lloway.github.io/diplom_blanchard/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/lorem-skrin.webp',
		title: 'Тест',
		subtitle: 'Loremipsun.net',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex + grid)',
		func: 'Choices, rangeslider',
		link: 'https://h0lloway.github.io/ccs-test/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/ЭПА.webp',
		title: 'Landing page',
		subtitle: 'Экспертно-Правовое Агенство',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex)',
		func: 'Табы, аккордеон, слайдеры, модальные окна',
		link: 'https://h0lloway.github.io/EPA/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/psycho.webp',
		title: 'Landing page',
		subtitle: 'Корпорация психологии',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex + grid)',
		func: 'Слайдер цены, бургер меню, модальные окна, табы',
		link: 'https://h0lloway.github.io/psychologists_v2/',
	},
	{
		type: 'email',
		display: 'none',
		img: 'files/img/portfolio/hilding-letter.webp',
		title: 'HTML письмо',
		subtitle: 'Hilding Anders',
		work: 'Верстка',
		tech: 'Резиновая',
		func: 'email-рассылка',
		link: 'https://h0lloway.github.io/hilding-letter/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/gamevendor.webp',
		title: 'Интернет-магазин',
		subtitle: 'GameVendor',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex + grid)',
		func: 'Слайдер, селекты, добавление карточки, аккордион',
		link: 'https://h0lloway.github.io/gameVendor_page/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/tectum.webp',
		title: 'Веб-интерфейс',
		subtitle: 'Tectum',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(bootstrap)',
		func: 'Адаптивная таблица, бургер меню, кастомные селекты',
		link: 'https://h0lloway.github.io/tectum/',
	},
	{
		type: 'email',
		display: 'none',
		img: 'files/img/portfolio/rosseti-letter.webp',
		title: 'HTML письмо',
		subtitle: 'Rosseti',
		work: 'Верстка',
		tech: 'Резиновая',
		func: 'email-рассылка',
		link: 'https://h0lloway.github.io/rosseti-letter/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/for-teachers.webp',
		title: 'Landing page',
		subtitle: 'Мы - учителям',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex + grid)',
		func: 'Слайдеры, бургер меню',
		link: 'https://h0lloway.github.io/for-teachers/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/highpass.webp',
		title: 'Сайт фотостудии',
		subtitle: 'HighPass',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex + grid)',
		func: 'Сайт фотостудии',
		link: 'https://h0lloway.github.io/high-pass-work/',
	},
	{
		type: 'html',
		display: 'block',
		img: 'files/img/portfolio/furino.webp',
		title: 'Интернет-магазин',
		subtitle: 'Furino',
		work: 'Адаптивная верстка',
		tech: 'HTML + CSS(flex + grid)',
		func: 'Слайдер, кнопки, галерея',
		link: 'https://h0lloway.github.io/Furino/',
	},
	{
		type: 'email',
		display: 'none',
		img: 'files/img/portfolio/eldorado.webp',
		title: 'HTML письмо',
		subtitle: 'Эльдорадо',
		work: 'Верстка',
		tech: 'Адаптивно',
		func: 'Рассылка',
		link: 'https://h0lloway.github.io/testmaileldorado/',
	},
	{
		type: 'email',
		display: 'none',
		img: 'files/img/portfolio/htmlletter.webp',
		title: 'HTML письмо',
		subtitle: 'Software depot',
		work: 'Верстка',
		tech: 'Резиновая',
		func: 'Рассылка',
		link: 'https://h0lloway.github.io/software-depot-letter/',
	},
	{
		type: 'email',
		display: 'none',
		img: 'files/img/portfolio/blanchard-letter.webp',
		title: 'HTML письмо',
		subtitle: 'Blanchard',
		work: 'Верстка',
		tech: 'Адаптивно',
		func: 'Рассылка',
		link: 'https://h0lloway.github.io/blanchard-letter/',
	},
	{
		type: 'js',
		display: 'none',
		img: 'files/img/portfolio/Игра пары числе.webp',
		title: 'Игра',
		subtitle: 'Пары чисел',
		work: 'JavaScript',
		tech: '',
		func: 'Игра',
		link: 'https://h0lloway.github.io/couple_game/',
	},
]